# modules/glue/main.tf -- generated by pipeline-automator scaffold (project init)
# Glue ETL jobs for this data product. One aws_glue_job resource is created per
# entry in var.jobs via for_each. Job scripts are read from the scripts bucket at
# s3://{scripts_bucket_name}/scripts/{job_name}/{job_name}.py
# A job at the start of a chain may run on a schedule (var.scheduled_triggers);
# a job reading another job's output runs when that job succeeds
# (var.conditional_triggers). Every job runs with the Glue Data Catalog as its
# Spark catalog (--enable-glue-datacatalog), where a job whose output has a Hive
# table registers the partitions it wrote.

locals {
  common_tags = merge(var.tags, {
    Environment = var.environment
    ManagedBy   = "terraform"
  })
}

resource "aws_glue_job" "etl" {
  for_each = var.jobs

  name         = "${var.name_prefix}-${each.key}"
  role_arn     = var.role_arn
  glue_version = "5.0"
  max_retries  = 0

  worker_type       = each.value.glue.worker_type
  number_of_workers = each.value.glue.number_of_workers

  execution_property {
    max_concurrent_runs = 2
  }

  command {
    name            = "glueetl"
    python_version  = "3"
    script_location = "s3://${var.scripts_bucket_name}/scripts/${each.key}/${each.key}.py"
  }

  default_arguments = merge(
    {
      "--job-language"                     = "python"
      "--enable-metrics"                   = "true"
      "--enable-continuous-cloudwatch-log" = "true"
      "--extra-py-files"                   = "s3://${var.scripts_bucket_name}/${var.package_object_key}"
      "--TempDir"                          = "s3://${var.scripts_bucket_name}/temp/"
      "--enable-glue-datacatalog"          = "true"
      "--environment"                      = var.environment
    },
    { for k, v in each.value.arguments : "--${k}" => v },
  )

  tags = local.common_tags
}

resource "aws_glue_trigger" "scheduled" {
  for_each = var.scheduled_triggers

  name     = "${var.name_prefix}-${each.key}-scheduled"
  type     = "SCHEDULED"
  schedule = each.value

  actions {
    job_name = aws_glue_job.etl[each.key].name
  }

  tags = local.common_tags
}

resource "aws_glue_trigger" "conditional" {
  for_each = var.conditional_triggers

  name = "${var.name_prefix}-${each.key}-after-${each.value}"
  type = "CONDITIONAL"

  predicate {
    conditions {
      job_name = aws_glue_job.etl[each.value].name
      state    = "SUCCEEDED"
    }
  }

  actions {
    job_name = aws_glue_job.etl[each.key].name
  }

  tags = local.common_tags
}
