# modules/glue/variables.tf -- generated by pipeline-automator scaffold (project init)

variable "name_prefix" {
  description = "Prefix applied to Glue job names (typically '<data_product>-<environment>')."
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
}

variable "jobs" {
  description = "ETL jobs keyed by job name: Glue workers, and the job's Glue arguments (names without '--'). Rebuilt from the job specs by engineering-automation."
  type = map(object({
    glue = object({
      worker_type       = string
      number_of_workers = number
    })
    arguments = map(string)
  }))
}

variable "scheduled_triggers" {
  description = "Jobs started on a schedule: job name to an AWS cron expression, e.g. cron(0 6 * * ? *)."
  type        = map(string)
  default     = {}
}

variable "conditional_triggers" {
  description = "Jobs started when another job's run succeeds: job name to the name of the job it runs after."
  type        = map(string)
  default     = {}
}

variable "role_arn" {
  description = "ARN of the IAM role the Glue jobs assume."
  type        = string
}

variable "scripts_bucket_name" {
  description = "Name of the S3 bucket holding job scripts and the shared temp directory."
  type        = string
}

variable "package_object_key" {
  description = "S3 key of the shared first-party code zip passed to every job via --extra-py-files."
  type        = string
  default     = "lib/payroll_pipeline_prototype.zip"
}

variable "tags" {
  description = "Tags applied to all Glue job resources."
  type        = map(string)
  default     = {}
}
