# modules/iam/main.tf -- generated by pipeline-automator scaffold (project init)
# Execution role assumed by Glue jobs in this data product.
# Permissions follow least-privilege per medallion layer:
#   raw        → read-only (source of truth, never written by ETL)
#   preprocessed, processed → read-write (ETL output layers)
#   scripts    → read-only (Glue fetches its own script at job startup),
#                plus write under temp/ (the jobs' --TempDir, for shuffle and spill)

locals {
  common_tags = merge(var.tags, {
    Environment = var.environment
    ManagedBy   = "terraform"
  })
}

data "aws_iam_policy_document" "glue_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["glue.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "glue_execution" {
  name               = "${var.name_prefix}-glue-execution"
  assume_role_policy = data.aws_iam_policy_document.glue_assume.json
  tags               = local.common_tags
}

resource "aws_iam_role_policy_attachment" "glue_service" {
  role       = aws_iam_role.glue_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
}

data "aws_iam_policy_document" "s3_access" {
  statement {
    sid     = "RawReadOnly"
    effect  = "Allow"
    actions = ["s3:GetObject", "s3:ListBucket"]
    resources = [
      var.raw_bucket_arn,
      "${var.raw_bucket_arn}/*",
    ]
  }

  statement {
    sid    = "PreprocessedProcessedReadWrite"
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:PutObject",
      "s3:DeleteObject",
      "s3:ListBucket",
    ]
    resources = [
      var.preprocessed_bucket_arn,
      "${var.preprocessed_bucket_arn}/*",
      var.processed_bucket_arn,
      "${var.processed_bucket_arn}/*",
    ]
  }

  statement {
    sid     = "ScriptsReadOnly"
    effect  = "Allow"
    actions = ["s3:GetObject", "s3:ListBucket"]
    resources = [
      var.scripts_bucket_arn,
      "${var.scripts_bucket_arn}/*",
    ]
  }

  statement {
    sid       = "ScriptsTempWrite"
    effect    = "Allow"
    actions   = ["s3:PutObject", "s3:DeleteObject"]
    resources = ["${var.scripts_bucket_arn}/temp/*"]
  }
}

resource "aws_iam_policy" "s3_access" {
  name   = "${var.name_prefix}-glue-s3-policy"
  policy = data.aws_iam_policy_document.s3_access.json
  tags   = local.common_tags
}

resource "aws_iam_role_policy_attachment" "s3_access" {
  role       = aws_iam_role.glue_execution.name
  policy_arn = aws_iam_policy.s3_access.arn
}
