# modules/iam/variables.tf -- generated by pipeline-automator scaffold (project init)

variable "name_prefix" {
  description = "Prefix applied to IAM resource names (typically '<data_product>-<environment>')."
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
}

variable "raw_bucket_arn" {
  description = "ARN of the raw layer S3 bucket. Glue is granted read-only access."
  type        = string
}

variable "preprocessed_bucket_arn" {
  description = "ARN of the preprocessed layer S3 bucket. Glue is granted read-write access."
  type        = string
}

variable "processed_bucket_arn" {
  description = "ARN of the processed layer S3 bucket. Glue is granted read-write access."
  type        = string
}

variable "scripts_bucket_arn" {
  description = "ARN of the scripts S3 bucket. Glue is granted read-only access to fetch job scripts, and write access under temp/."
  type        = string
}

variable "tags" {
  description = "Tags applied to all resources in this module."
  type        = map(string)
  default     = {}
}
