# providers.tf -- generated by pipeline-automator scaffold (project init)
# Provider and backend configuration for the payroll_pipeline_prototype data pipeline.

terraform {
  required_version = ">= 1.10"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # S3-native state locking (Terraform >= 1.10): the lock is a conditional write
  # of a `.tflock` object beside the state, so no DynamoDB table is required.
  backend "s3" {
    bucket       = "payroll-pipeline-prototype-tfstate-bucket"
    key          = "payroll_pipeline_prototype/terraform.tfstate"
    region       = "eu-central-1"
    encrypt      = true
    use_lockfile = true
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      DataProduct = "payroll_pipeline_prototype"
      ManagedBy   = "terraform"
      Project     = "payroll_pipeline_prototype"
      Environment = var.environment
    }
  }
}
