"""The run record every ETL job in this project emits: one line of JSON per run.

Generated by `engineering-automation scaffold create-project`. Edit the scaffold template,
not this file.

Each job's `run()` parses its arguments and resolves its processing dates, then opens
`job_run()`, which emits exactly one record when the run ends, whether it succeeded or
failed, and wraps each of read, transform and write in `phase()`.

Two deliberate omissions, decided rather than overlooked:
    * No `GlueContext` / `DynamicFrame`. Every read and write in this package
      uses the plain Spark SQL API, so the Glue wrapper layer buys nothing.
    * No `Job.init()` / `Job.commit()`. Those exist to drive Glue job
      bookmarks. The processing dates are resolved explicitly from the job's
      arguments, so bookmarks would duplicate -- and eventually contradict --
      that logic. The absence of `job.commit()` is intentional.
"""

import json
import time
import traceback
from argparse import Namespace
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from typing import Any

RUN_RECORD_PREFIX = "RUN_RECORD"


@dataclass
class RunRecord:
    """One structured summary of a single job execution.

    Mutable by design: `job_run` fills in the outcome fields, `phase` tracks
    which stage is executing, and the job body may attach anything else to
    `metrics`.
    """

    job_name: str
    started_at: str
    processing_dates: list[str]
    status: str = "RUNNING"
    phase: str | None = None
    glue_job_name: str | None = None
    glue_run_id: str | None = None
    environment: str | None = None
    finished_at: str | None = None
    duration_seconds: float | None = None
    phase_durations: dict[str, float] = field(default_factory=dict)
    error_type: str | None = None
    error_message: str | None = None
    traceback: str | None = None
    metrics: dict[str, Any] = field(default_factory=dict)


@contextmanager
def phase(record: RunRecord, name: str) -> Iterator[None]:
    """Mark which stage of the job is executing, and time it.

    Nothing resets `record.phase` on the way out of a failure, so it still
    names the stage that was running when the exception escaped. `job_run`
    clears it on success, so a non-null phase on an emitted record always
    means "this is where it broke".
    """
    record.phase = name
    started = time.monotonic()
    try:
        yield
    finally:
        record.phase_durations[name] = round(time.monotonic() - started, 3)


@contextmanager
def job_run(job_name: str, args: Namespace, processing_dates: list[str]) -> Iterator[RunRecord]:
    """Wrap one run of a job so that exactly one run record is emitted.

    The job parses its arguments and resolves its processing dates before it opens
    this, so a bad date argument fails the run without a record; Glue still marks the
    run failed and logs the error. Read, transform and write all run inside it.

    On failure the record is completed with the error and emitted, then the
    exception is re-raised unchanged -- swallowing it would leave Glue
    reporting SUCCEEDED for a run that produced nothing.

    Args:
        job_name: The job's name, i.e. its module name under `jobs/`. This is not
            the Glue resource name, which carries the `<product>-<env>` prefix and
            arrives separately as `--JOB_NAME`; both are recorded.
        args: The job's parsed arguments; their `JOB_NAME`, `JOB_RUN_ID` and
            `environment` are recorded.
        processing_dates: The dates the run processes, as YYYY-MM-DD strings.

    Yields:
        The mutable `RunRecord` for this run.
    """
    record = RunRecord(
        job_name=job_name,
        started_at=_utc_now_iso(),
        processing_dates=processing_dates,
        glue_job_name=args.JOB_NAME,
        glue_run_id=args.JOB_RUN_ID,
        environment=args.environment,
    )
    started = time.monotonic()
    try:
        yield record
    except BaseException as exc:
        record.status = "FAILED"
        record.error_type = type(exc).__name__
        record.error_message = str(exc)[:2000]
        record.traceback = traceback.format_exc()[-4000:]
        raise
    else:
        record.status = "SUCCEEDED"
        record.phase = None
    finally:
        record.finished_at = _utc_now_iso()
        record.duration_seconds = round(time.monotonic() - started, 3)
        emit_run_record(record)


def emit_run_record(record: RunRecord) -> None:
    """Write the run record to stdout as a single line of JSON.

    stdout is the whole transport. The Glue jobs set
    `--enable-continuous-cloudwatch-log`, so the driver's stdout streams to
    CloudWatch Logs with no extra wiring, no IAM beyond what the job already
    has, and nothing to fail independently of the job itself.

    The constant prefix makes the record addressable by a CloudWatch metric
    filter or a Logs Insights query without having to parse it out of the
    surrounding Spark noise.

    This record is for humans and observability only. Orchestration keys off
    Glue's own job-run state, which is set by the script's exit code -- which
    is why `job_run` re-raises rather than reporting failure only here.
    """
    payload = json.dumps(asdict(record), default=str, sort_keys=True)
    print(f"{RUN_RECORD_PREFIX} {payload}", flush=True)


def _utc_now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")
