# modules/catalog/main.tf -- generated by pipeline-automator scaffold (project init)
# Glue Data Catalog databases and Hive tables over the job outputs whose output
# contract says `table: hive`: one database per data layer holding a table, named
# after the layer's bucket, and one external parquet table per dataset, located at
# the dataset's S3 folder. The job writing a dataset registers its partitions.

locals {
  common_tags = merge(var.tags, {
    Environment = var.environment
    ManagedBy   = "terraform"
  })

  layers = toset([for t in values(var.tables) : t.layer])
}

resource "aws_glue_catalog_database" "layers" {
  for_each = local.layers

  name = replace(var.bucket_names[each.key], "-", "_")
  tags = local.common_tags
}

resource "aws_glue_catalog_table" "tables" {
  for_each = var.tables

  name          = each.value.dataset
  database_name = aws_glue_catalog_database.layers[each.value.layer].name
  description   = each.value.description
  table_type    = "EXTERNAL_TABLE"

  parameters = {
    EXTERNAL       = "TRUE"
    classification = "parquet"
  }

  dynamic "partition_keys" {
    for_each = each.value.partition_keys
    content {
      name    = partition_keys.value.name
      type    = partition_keys.value.type
      comment = partition_keys.value.comment
    }
  }

  storage_descriptor {
    location      = "s3://${var.bucket_names[each.value.layer]}/${each.value.dataset}/"
    input_format  = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
    }

    dynamic "columns" {
      for_each = each.value.columns
      content {
        name       = columns.value.name
        type       = columns.value.type
        comment    = columns.value.comment
        parameters = { nullable = tostring(columns.value.nullable) } # for documentation only
      }
    }
  }
}
