# modules/catalog/outputs.tf -- generated by pipeline-automator scaffold (project init)

output "database_names" {
  description = "Map of layer to Glue database name."
  value       = { for k, v in aws_glue_catalog_database.layers : k => v.name }
}

output "table_names" {
  description = "Map of '<layer>/<dataset>' to the table's full name, '<database>.<table>'."
  value       = { for k, v in aws_glue_catalog_table.tables : k => "${v.database_name}.${v.name}" }
}
