# modules/catalog/variables.tf -- generated by pipeline-automator scaffold (project init)

variable "tables" {
  description = "Hive tables keyed by '<layer>/<dataset>'. Rebuilt from the output contracts by engineering-automation."
  type = map(object({
    layer       = string
    dataset     = string
    description = string
    partition_keys = list(object({
      name    = string
      type    = string
      comment = string
    }))
    columns = list(object({
      name     = string
      type     = string
      nullable = bool
      comment  = string
    }))
  }))
}

variable "bucket_names" {
  description = "Bucket name per layer, from the S3 module. Sets each table's location and its database's name."
  type        = map(string)
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
}

variable "tags" {
  description = "Tags applied to the catalog databases (Glue tables take no tags)."
  type        = map(string)
  default     = {}
}
